2021-12-22 21:20:47.667 | INFO     | __main__:evaluate:13 - building test dataset ...
0it [00:00, ?it/s]11386it [00:00, 810845.13it/s]
2021-12-22 21:20:47.682 | INFO     | __main__:evaluate:26 - loading best_model ...
2021-12-22 21:20:50.142 | INFO     | __main__:evaluate:29 - start testing ...
2021-12-22 21:20:50.143 | INFO     | utils:__call__:69 - Information Retrieval Evaluation on test dataset:
Batches:   0%|          | 0/2 [00:00<?, ?it/s]Batches:  50%|█████     | 1/2 [00:00<00:00,  2.50it/s]Batches: 100%|██████████| 2/2 [00:00<00:00,  4.54it/s]
Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]Corpus Chunks: 100%|██████████| 1/1 [00:08<00:00,  8.54s/it]Corpus Chunks: 100%|██████████| 1/1 [00:08<00:00,  8.54s/it]
2021-12-22 21:21:03.766 | INFO     | utils:compute_metrices:131 - Queries: 54
2021-12-22 21:21:03.767 | INFO     | utils:compute_metrices:132 - Corpus: 5695

/data/private/zhy2018/projects/IR_COMPETITION/src/utils.py:154: RuntimeWarning: invalid value encountered in double_scalars
  ndcg_value = self.compute_dcg_at_k(predicted_relevance, k_val) / self.compute_dcg_at_k(true_relevances, k_val)
2021-12-22 21:21:03.769 | INFO     | utils:compute_metrices:137 - Score-Function: cos_sim
2021-12-22 21:21:03.769 | INFO     | utils:output_scores:163 - NDCG@10: 0.8676
